name: spacemaker
description: SpaceMaker — Swipe left for storage
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.3
  photo_manager: ^3.6.3
  video_player: ^2.9.2
  permission_handler: ^11.3.1
  intl: ^0.20.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
